<script setup lang="ts">
import { site, ordered, assetVariant, assetSrcSet } from '~/lib/site'
const creations = ordered(site.creations.filter((item) => item.featured)).slice(0, 4)
const album = ordered(site.albums.filter((item) => item.featured))[0]
const fitness = ordered(site.fitness.entries.filter((item) => item.featured)).slice(0, 3)
const fitnessPhotos = fitness.flatMap((entry) => entry.photos.map((photo) => ({ ...photo, title: entry.title }))).slice(0, 3)
useSeoMeta({ title: '虚宁 · xvyin.com', description: site.settings.intro, ogTitle: '虚宁 · xvyin.com', ogDescription: site.settings.intro })
</script>
<style src="~/assets/freepaper.css"></style>
<template><section class="hero"><div class="hero-copy"><h1 aria-label="Hello! I am 虚宁"><span class="hello">Hello! I am </span><span class="name">虚宁</span></h1><p v-if="site.settings.intro" class="hero-intro">{{ site.settings.intro }}</p><div class="actions"><NuxtLink class="button primary" to="/creations">探索创作<SiteIcon name="arrow" /></NuxtLink><NuxtLink class="text-link" to="/about">关于我<SiteIcon name="external" :size="18" /></NuxtLink></div></div></section>
<section class="section interaction" aria-labelledby="interaction-title"><div class="section-heading"><h2 id="interaction-title">听歌，也聊几句</h2><p class="interaction-note">音乐与文字，都是生活的回声。</p></div><div class="interaction-grid"><MusicPlayer /><GuestbookPanel /></div></section>
<section id="creations" class="section"><div class="section-heading"><h2>精选创作<span class="dot" aria-hidden="true" /></h2><NuxtLink class="text-link" to="/creations">全部创作<SiteIcon name="external" :size="18" /></NuxtLink></div><div class="creations-body" :class="{ 'has-creations': creations.length, 'has-many-creations': creations.length > 1 }"><div v-if="creations.length" class="creations-grid"><CreationCard v-for="(entry, i) in creations" :key="entry.id" :entry="entry" :featured="i === 0" /></div><div v-else class="empty-state"><h3>创作慢慢积累。</h3><p>这里暂时没有精选创作。</p><NuxtLink class="text-link" to="/creations">浏览全部创作<SiteIcon name="arrow" :size="18" /></NuxtLink></div><figure class="paper-aside"><img src="/brand/ink-branch.webp" width="1536" height="1024" alt="" loading="lazy" decoding="async"><figcaption><span>一些想法，</span><span>慢慢写下来。</span></figcaption></figure></div></section>
<section id="photography" class="section"><div class="section-heading"><h2>用镜头，收藏片刻<span class="dot" aria-hidden="true" /></h2><NuxtLink class="text-link" to="/photography">全部摄影<SiteIcon name="external" :size="18" /></NuxtLink></div><div v-if="album" class="photo-layout"><NuxtLink :to="`/photography/${album.slug}`"><img v-if="assetVariant(album.coverAssetId || album.photos[0]?.assetId)" :src="assetVariant(album.coverAssetId || album.photos[0]?.assetId)?.url" :srcset="assetSrcSet(album.coverAssetId || album.photos[0]?.assetId)" sizes="(max-width: 700px) calc(100vw - 40px), (max-width: 1100px) 60vw, 760px" decoding="async" :width="assetVariant(album.coverAssetId || album.photos[0]?.assetId)?.width" :height="assetVariant(album.coverAssetId || album.photos[0]?.assetId)?.height" :alt="album.title" loading="lazy"></NuxtLink><div class="photo-copy"><h3>{{ album.title }}</h3><p>{{ album.description }}</p><NuxtLink class="text-link" :to="`/photography/${album.slug}`">打开这个系列<SiteIcon name="arrow" :size="18" /></NuxtLink></div></div><div v-else class="empty-state"><h3>等待下一束光。</h3><p>暂时没有精选摄影系列。</p></div></section>
<section v-if="site.fitness.settings.enabled" class="section"><div :class="['fitness-layout', { 'fitness-empty-layout': !fitnessPhotos.length }]"><div><h2>把坚持，<br>放进日常<span class="dot" aria-hidden="true" /></h2><p>{{ site.fitness.settings.intro }}</p><FitnessCounter :start-date="site.fitness.settings.startDate" /><NuxtLink class="text-link" to="/fitness">查看健身记录<SiteIcon name="external" :size="18" /></NuxtLink></div><PhotoGallery v-if="fitnessPhotos.length" :photos="fitnessPhotos" layout="continuous" /><p v-else class="muted fitness-empty-copy">训练影像还在整理中。<br>有了公开记录，会在这里慢慢展开。</p></div></section>

<section v-if="site.settings.contactEnabled" id="contact" class="section contact-section"><div class="contact-copy"><h2>有想法，<br>就聊一聊<span class="dot" aria-hidden="true" /></h2><p>关于创作、技术，或者一句简单的问候。欢迎写信给我。</p><p class="small muted">这里的消息是私信，不会进入公开留言。</p></div><ContactForm /></section></template>
