<script setup lang="ts">
import { ref } from 'vue';
import { type ContentBlock } from '@xvyin/contracts';
import RichTextEditor from './RichTextEditor.vue';
import AssetField from './AssetField.vue';
import { externalMediaLink } from '../media';
import { providerContentId } from '../provider-input';
import MediaPicker from './MediaPicker.vue';
import type { MediaItem } from '../api';
const props=defineProps<{modelValue:ContentBlock[]}>();
const emit=defineEmits<{'update:modelValue':[blocks:ContentBlock[]]}>();
const labels:Record<ContentBlock['type'],string>={richtext:'富文本',image:'图片',gallery:'图集',audio:'音频',video:'视频',quote:'引用',code:'代码',file:'附件'};
const dragged=ref<number|null>(null);
const galleryPicker = ref<Extract<ContentBlock,{type:'gallery'}> | null>(null);
function addGallery(items: MediaItem[]) {
  const block = galleryPicker.value; if (!block) return;
  const existing = new Set(block.items.map(item => item.assetId));
  for (const item of items) if (block.items.length < 100 && item.kind === 'image' && (item.processingStatus || item.status) === 'ready' && !existing.has(item.id)) {
    existing.add(item.id); block.items.push({ assetId: item.id, alt: (item.originalName || '照片').replace(/\.[^.]+$/, '').slice(0, 500), caption: '', sortOrder: block.items.length });
  }
}
function add(type:ContentBlock['type']) {
  if(props.modelValue.length>=200)return;const id=crypto.randomUUID();let block:ContentBlock;
  switch(type){
    case 'richtext':block={id,type,document:{type:'doc',content:[{type:'paragraph',content:[]}]}};break;
    case 'image':block={id,type,assetId:'',variantRole:'content',alt:'',caption:'',alignment:'center'};break;
    case 'gallery':block={id,type,items:[],layout:'grid'};break;
    case 'audio':block={id,type,assetId:'',title:'',artist:'',downloadAllowed:false};break;
    case 'video':block={id,type,assetId:'',posterAssetId:''};break;
    case 'quote':block={id,type,text:'',attribution:''};break;
    case 'code':block={id,type,language:'text',code:''};break;
    case 'file':block={id,type,assetId:'',label:''};break;
  }
  emit('update:modelValue',[...props.modelValue,block]);
}
function move(index:number,target:number){if(target<0||target>=props.modelValue.length||index===target)return;const blocks=[...props.modelValue];const moved=blocks.splice(index,1)[0];if(!moved)return;blocks.splice(target,0,moved);emit('update:modelValue',blocks);}
function remove(index:number){if(!window.confirm('移除这个内容块？保存草稿前仍可刷新恢复上次保存的版本。'))return;emit('update:modelValue',props.modelValue.filter((_,i)=>i!==index));}
function source(block:Extract<ContentBlock,{type:'audio'|'video'}>,event:Event){const mode=(event.target as HTMLSelectElement).value;if(mode==='provider'){delete block.assetId;block.providerRef={provider:block.type==='audio'?'netease':'bilibili',contentId:''};}else{delete block.providerRef;block.assetId='';}}
function galleryMove(block:Extract<ContentBlock,{type:'gallery'}>,index:number,direction:number){const target=index+direction;if(target<0||target>=block.items.length)return;const moved=block.items.splice(index,1)[0];if(!moved)return;block.items.splice(target,0,moved);block.items.forEach((item,i)=>item.sortOrder=i);}
</script>
<template><section class="block-editor"><div class="flex between"><h2>正文内容</h2><span class="hint">{{ modelValue.length }} / 200 个内容块</span></div><div class="block-palette"><button v-for="(label,type) in labels" :key="type" type="button" :disabled="modelValue.length>=200" @click="add(type)">＋ {{ label }}</button></div><div v-if="!modelValue.length" class="empty"><h3>从一段文字开始</h3><p>添加内容块，可以混排文字、图片、音频与视频。</p><button type="button" @click="add('richtext')">添加富文本</button></div><article v-for="(block,index) in modelValue" :key="block.id" class="content-block" @dragover.prevent @drop.prevent="dragged!==null&&move(dragged,index);dragged=null"><header class="block-head"><strong><span class="drag-handle" draggable="true" title="拖动内容块排序" aria-hidden="true" @dragstart="dragged=index">⠿</span><span class="block-number">{{ String(index+1).padStart(2,'0') }}</span>{{ labels[block.type] }}</strong><div class="row-actions flex"><button type="button" :disabled="index===0" :aria-label="`将第${index+1}个内容块上移`" @click="move(index,index-1)">↑</button><button type="button" :disabled="index===modelValue.length-1" :aria-label="`将第${index+1}个内容块下移`" @click="move(index,index+1)">↓</button><button type="button" class="quiet danger" :aria-label="`移除第${index+1}个内容块`" @click="remove(index)">移除</button></div></header><div class="block-body">
<RichTextEditor v-if="block.type==='richtext'" v-model="block.document" :label="`第${index+1}块富文本`"/>
<template v-else-if="block.type==='image'"><AssetField v-model="block.assetId" label="图片" kind="image"/><div class="form-grid mt16"><label class="field">替代文字<input v-model="block.alt" maxlength="500" required placeholder="说明图片内容"></label><label class="field">对齐方式<select v-model="block.alignment"><option value="left">左对齐</option><option value="center">居中</option><option value="wide">宽图</option></select></label><label class="field span2">图注<textarea v-model="block.caption" maxlength="1000"></textarea></label></div></template>
<template v-else-if="block.type==='gallery'"><label class="field">图集布局<select v-model="block.layout"><option value="grid">网格</option><option value="columns">分栏</option><option value="stack">逐张大图</option></select></label><div v-for="(item,i) in block.items" :key="i" class="nested-card"><div class="flex between"><strong>图片 {{ i+1 }}</strong><div class="flex"><button type="button" :disabled="i===0" aria-label="图片上移" @click="galleryMove(block,i,-1)">↑</button><button type="button" :disabled="i===block.items.length-1" aria-label="图片下移" @click="galleryMove(block,i,1)">↓</button><button type="button" class="danger" @click="block.items.splice(i,1);block.items.forEach((row,j)=>row.sortOrder=j)">移除</button></div></div><AssetField v-model="item.assetId" label="图集图片" kind="image"/><label class="field">替代文字<input v-model="item.alt" maxlength="500" required></label><label class="field">图注<input v-model="item.caption" maxlength="1000"></label></div><button type="button" class="mt16" :disabled="block.items.length>=100" @click="galleryPicker=block">＋ 上传或批量选择图片</button></template>
<template v-else-if="block.type==='audio'||block.type==='video'"><label class="field">媒体来源<select :value="block.providerRef?'provider':'asset'" @change="source(block,$event)"><option value="asset">本站媒体库</option><option value="provider">外部平台内容</option></select></label><div v-if="block.providerRef" class="form-grid mt16"><label class="field">平台<select v-model="block.providerRef.provider"><template v-if="block.type==='audio'"><option value="netease">网易云音乐</option><option value="tencent">QQ 音乐</option></template><template v-else><option value="bilibili">哔哩哔哩</option><option value="youtube">YouTube</option><option value="douyin">抖音</option></template></select></label><label class="field">视频 / 音频链接或内容 ID<input v-model="block.providerRef.contentId" placeholder="粘贴平台完整链接，或内容编号" maxlength="2000" required @blur="block.providerRef.contentId=providerContentId(block.providerRef.provider,block.providerRef.contentId)"></label><a v-if="externalMediaLink(block.providerRef)" class="button span2" :href="externalMediaLink(block.providerRef)" target="_blank" rel="noopener noreferrer">到原平台查看{{block.type==='audio'?'音频':'视频'}} ↗</a><p v-if="block.type==='video'" class="hint span2">支持 BiliBili 完整视频链接或 BV / av 编号、YouTube 链接、抖音完整视频链接或数字视频编号。抖音分享短链请先打开，再复制 /video/ 完整地址。发布后访客可点击加载官方播放器，在本站观看；仍保留原平台入口。无需上传本站视频文件，封面可选；BiliBili 多 P 视频默认第一集。</p></div><AssetField v-else :model-value="block.assetId" :label="block.type==='audio'?'音频文件':'视频文件'" :kind="block.type" @update:model-value="value=>block.assetId=value??undefined"/>
<template v-if="block.type==='audio'"><div class="form-grid mt16"><label class="field">音频标题<input v-model="block.title" maxlength="120" required></label><label class="field">作者 / 艺术家<input v-model="block.artist" maxlength="120"></label></div><AssetField :model-value="block.coverAssetId" label="封面，可选" kind="image" optional @update:model-value="value=>block.coverAssetId=value??undefined"/><label class="check mt16"><input type="checkbox" v-model="block.downloadAllowed">允许下载公开播放文件</label></template>
<template v-else><AssetField :model-value="block.posterAssetId" :label="block.providerRef?'视频封面，可选':'视频封面'" kind="image" :optional="!!block.providerRef" @update:model-value="value=>block.posterAssetId=value??undefined"/><AssetField :model-value="block.captionsAssetId" label="WebVTT 字幕，可选" kind="file" optional @update:model-value="value=>block.captionsAssetId=value??undefined"/><label class="field">画面宽高比，可选<input v-model.number="block.aspectRatio" type="number" min="0.1" max="10" step="0.01" placeholder="例如 1.78"></label></template><label class="field mt16">文字稿，可留空<textarea v-model="block.transcript" maxlength="32000" rows="5" placeholder="填写真实文字稿；未提供时不宣称已有字幕"></textarea></label></template>
<template v-else-if="block.type==='quote'"><label class="field">引用内容<textarea v-model="block.text" rows="5" maxlength="5000" required></textarea></label><div class="form-grid mt16"><label class="field">出处 / 作者<input v-model="block.attribution" maxlength="300"></label><label class="field">来源链接，可选<input v-model="block.sourceUrl" type="url" placeholder="https://"></label></div></template>
<template v-else-if="block.type==='code'"><div class="form-grid"><label class="field">语言<input v-model="block.language" maxlength="30" placeholder="python / javascript / text"></label><label class="field">文件名，可选<input v-model="block.filename" maxlength="200"></label></div><label class="field mt16">代码内容<textarea v-model="block.code" class="code-input" spellcheck="false" rows="9" maxlength="64000" required></textarea></label><p class="hint mt8">作为文本展示，不执行其中的代码。</p></template>
<template v-else-if="block.type==='file'"><AssetField v-model="block.assetId" label="附件" kind="file"/><label class="field">下载按钮文字<input v-model="block.label" maxlength="120" required></label><label class="field">附件说明<textarea v-model="block.description" maxlength="1000"></textarea></label></template>
</div></article><MediaPicker v-if="galleryPicker" kind="image" title="添加图集照片" multiple :max-selected="100-galleryPicker.items.length" :exclude-ids="galleryPicker.items.map(item=>item.assetId)" @close="galleryPicker=null" @select-many="addGallery"/></section></template>
