<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';import {api,dateTime,errorMessage,visibilityLabel} from '../api';
interface CommentRecord{id:string;version:number;nickname:string;body:string;status:string;targetType:string;targetId:string|null;createdAt:string}
interface ContactRecord{id:string;nickname:string;email:string;message:string;createdAt:string}
const tab=ref<'comments'|'contacts'>('comments');const comments=ref<CommentRecord[]>([]);const contacts=ref<ContactRecord[]>([]);const loading=ref(true);const busy=ref('');const issue=ref('');const filter=ref('pending');const query=ref('');const cursor=ref<string>();
const filtered=computed(()=>comments.value.filter(item=>(filter.value==='all'||item.status===filter.value)&&`${item.nickname} ${item.body}`.toLowerCase().includes(query.value.toLowerCase())));
async function load(more=false){loading.value=true;issue.value='';try{const response=await api.request<CommentRecord[]|ContactRecord[]>(`/admin/${tab.value}${more&&cursor.value?`?cursor=${encodeURIComponent(cursor.value)}`:''}`);if(tab.value==='comments')comments.value=more?[...comments.value,...response.data as CommentRecord[]]:response.data as CommentRecord[];else contacts.value=more?[...contacts.value,...response.data as ContactRecord[]]:response.data as ContactRecord[];cursor.value=response.meta.nextCursor;}catch(error){issue.value=errorMessage(error);}finally{loading.value=false;}}
async function moderate(comment:CommentRecord,status:'approved'|'rejected'|'hidden'){busy.value=comment.id;issue.value='';try{const response=await api.request<CommentRecord>(`/admin/comments/${comment.id}`,{method:'PATCH',body:{status,expectedVersion:comment.version}});const index=comments.value.findIndex(item=>item.id===comment.id);if(index>=0)comments.value[index]=response.data;}catch(error){issue.value=errorMessage(error);}finally{busy.value='';}}
function switchTab(value:'comments'|'contacts'){tab.value=value;cursor.value=undefined;load();}onMounted(()=>load());
</script>
<template><div><div class="tabs" role="tablist" aria-label="留言与联系"><button role="tab" :aria-selected="tab==='comments'" :class="{active:tab==='comments'}" @click="switchTab('comments')">公开留言审核</button><button role="tab" :aria-selected="tab==='contacts'" :class="{active:tab==='contacts'}" @click="switchTab('contacts')">私密联系</button></div><p class="hint mt16">{{tab==='comments'?'访客留言审核通过后才会公开。隐藏或拒绝的留言不进入首页弹幕。':'联系表单内容仅管理员可见。这里不自动发送任何回复。'}}</p><div class="toolbar mt24"><label class="search"><span class="sr-only">搜索留言</span><input v-if="tab==='comments'" v-model="query" type="search" placeholder="搜索昵称或内容"></label><select v-if="tab==='comments'" v-model="filter" aria-label="审核状态"><option value="pending">待审核</option><option value="all">全部状态</option><option value="approved">已通过</option><option value="rejected">已拒绝</option><option value="hidden">已隐藏</option></select><button :disabled="loading" @click="load()">刷新</button></div><p v-if="issue" class="notice error mt16" role="alert">{{issue}}</p><p v-if="loading" class="loading" role="status">正在读取…</p><template v-else-if="tab==='comments'"><div v-if="!filtered.length" class="empty mt24"><h3>{{comments.length?'没有符合筛选的留言':'还没有访客留言'}}</h3><p>新的真实留言会在这里等待审核。</p></div><article v-for="comment in filtered" :key="comment.id" class="panel comment-card mt16"><div class="flex between"><strong>{{comment.nickname||'匿名访客'}}</strong><span class="badge">{{visibilityLabel(comment.status)}}</span></div><p class="comment-body mt16">{{comment.body}}</p><div class="flex between mt24"><small class="hint">{{dateTime(comment.createdAt)}} · {{comment.targetType==='guestbook'?'首页留言':comment.targetType==='creation'?'创作讨论':'摄影讨论'}}</small><div class="flex"><button v-if="comment.status!=='approved'" class="primary" :disabled="busy===comment.id" @click="moderate(comment,'approved')">通过并公开</button><button v-if="comment.status!=='rejected'" :disabled="busy===comment.id" @click="moderate(comment,'rejected')">拒绝</button><button v-if="comment.status==='approved'" :disabled="busy===comment.id" @click="moderate(comment,'hidden')">隐藏</button></div></div></article></template><template v-else><div v-if="!contacts.length" class="empty mt24"><h3>还没有收到联系</h3><p>访客提交的私密联系会显示在这里。</p></div><article v-for="contact in contacts" :key="contact.id" class="panel comment-card mt16"><div class="flex between"><strong>{{contact.nickname||'未填写姓名'}}</strong><small class="hint">{{dateTime(contact.createdAt)}}</small></div><p class="mono mt8">{{contact.email}}</p><p class="comment-body mt24">{{contact.message}}</p></article></template><button v-if="cursor" class="mt24" :disabled="loading" @click="load(true)">加载更多</button></div></template>
