<script setup lang="ts">
import { computed, ref } from 'vue';
import type { FitnessPhotoDraft } from '@xvyin/contracts';
import AssetField from './AssetField.vue';
const props=defineProps<{modelValue:FitnessPhotoDraft[]}>();const emit=defineEmits<{'update:modelValue':[value:FitnessPhotoDraft[]]}>();const dragged=ref<number|null>(null);
function move(index:number,to:number){if(to<0||to>=props.modelValue.length)return;const photos=[...props.modelValue];const moved=photos.splice(index,1)[0];if(!moved)return;photos.splice(to,0,moved);emit('update:modelValue',photos.map((photo,i)=>({...photo,sortOrder:i})));}
function newId(){return crypto.randomUUID();}
function remove(index:number){emit('update:modelValue',props.modelValue.filter((_,i)=>i!==index).map((photo,i)=>({...photo,sortOrder:i})));}
const selected = computed(() => props.modelValue.filter(photo => photo.status === 'published').length);
const availableDrafts = computed(() => props.modelValue.filter(photo => photo.status === 'draft' && photo.assetId).length);
function includeDrafts(){emit('update:modelValue',props.modelValue.map(photo => photo.status === 'draft' && photo.assetId ? {...photo,status:'published' as const} : photo));}
</script>

<style scoped>
.photo-publication{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-top:20px;padding:18px 0;border-block:1px solid var(--line);font-size:13px}.photo-publication>div{min-width:0}.photo-publication p{font-size:12px;color:var(--muted);line-height:1.8;margin-top:6px;max-width:56ch}.photo-publication.none-selected strong{color:var(--red)}.photo-publication>button{flex-shrink:0;font-size:12px}.photo-state{font-size:11px;font-weight:400;margin-left:12px;color:var(--muted)}@media(max-width:780px){.photo-publication{align-items:flex-start;flex-direction:column;gap:12px}.photo-publication>button{max-width:100%;white-space:normal}.photo-state{display:block;margin:5px 0 0}}
</style>
<template><section><div class="flex between"><h2>照片与图注</h2><button type="button" :disabled="modelValue.length>=100" @click="emit('update:modelValue',[...modelValue,{id:newId(),assetId:'',alt:'',caption:'',photoDate:null,sortOrder:modelValue.length,featured:false,status:'draft'}])">＋ 添加照片</button></div><p class="hint mt16">从统一媒体库关联原有素材。拍摄日期未知时留空，不以上传时间替代。</p><div v-if="!modelValue.length" class="empty mt16"><h3>还没有关联照片</h3><p>添加照片、补充图注，再预览和发布。</p></div><div v-if="modelValue.length" class="photo-publication" :class="{ 'none-selected': !selected }"><div><strong>{{ selected }} / {{ modelValue.length }} 张照片将随记录公开</strong><p>保存仍是私有草稿。只有选为“随本条记录发布”的照片会进入网站；隐藏照片保持私有。</p></div><button v-if="availableDrafts" type="button" @click="includeDrafts">让 {{ availableDrafts }} 张草稿照片随记录发布</button></div><article v-for="(photo,index) in modelValue" :key="photo.id" class="content-block mt16" @dragover.prevent @drop.prevent="dragged!==null&&move(dragged,index);dragged=null"><header class="block-head"><strong><span draggable="true" class="drag-handle" aria-hidden="true" @dragstart="dragged=index">⠿</span>照片 {{ index+1 }} <span class="photo-state">{{ {draft:'暂留草稿',published:'随记录公开',hidden:'已隐藏'}[photo.status] }}</span></strong><div class="flex row-actions"><button type="button" :disabled="index===0" aria-label="照片上移" @click="move(index,index-1)">↑</button><button type="button" :disabled="index===modelValue.length-1" aria-label="照片下移" @click="move(index,index+1)">↓</button><button type="button" class="danger" @click="remove(index)">移除</button></div></header><div class="block-body"><AssetField v-model="photo.assetId" label="照片" kind="image"/><div class="form-grid mt16"><label class="field">替代文字<input v-model="photo.alt" maxlength="500" required placeholder="描述画面内容"></label><label class="field">拍摄日期，可留空<input :value="photo.photoDate??''" type="date" @input="photo.photoDate=($event.target as HTMLInputElement).value||null"></label><label class="field">发布状态<select v-model="photo.status"><option value="draft">暂留草稿</option><option value="published">随本条记录发布</option><option value="hidden">隐藏</option></select></label><label class="field span2">图注<textarea v-model="photo.caption" maxlength="1000" rows="3"></textarea></label></div><label class="check mt16"><input v-model="photo.featured" type="checkbox">在首页精选中使用</label></div></article></section></template>
