<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { api, dateTime, errorMessage, type ReleaseJob } from '../api';
export interface ReleaseChange { collection: 'creations'|'albums'|'fitness'|'playlists'|'settings'; id: string; version: number; action: 'publish'|'hide' }
const props=defineProps<{changes?:ReleaseChange[]}>();
const emit=defineEmits<{close:[];activated:[];preview:[releaseId:string]}>();
const dialog=ref<HTMLDialogElement>(); const jobs=ref<ReleaseJob[]>([]); const selected=ref<ReleaseJob|null>(null); const activeId=ref<string|null>(null); const busy=ref(false); const issue=ref(''); const loading=ref(true); let timer:ReturnType<typeof setTimeout>|undefined; let alive=true;
const labels:Record<string,string>={live:'正在使用',activating:'正在切换',reconciling:'正在确认切换结果',queued:'等待生成',building:'正在生成页面',rendering:'正在生成页面',validating:'正在校验',uploading:'正在保存页面',ready:'待预览与确认',active:'正在使用',published:'已发布',failed:'发布失败',cancelled:'已取消',superseded:'已有更新版本'};
function statusLabel(status:string){return labels[status]??status;}
async function load(){loading.value=true;issue.value='';try{const response=await api.request<ReleaseJob[]>('/admin/releases');jobs.value=response.data;activeId.value=response.meta.activeReleaseId??null;}catch(error){issue.value=errorMessage(error);}finally{loading.value=false;}}
function poll(){if(timer)clearTimeout(timer);if(!alive||!selected.value||['ready','live','active','published','failed','cancelled','superseded'].includes(selected.value.status))return;timer=setTimeout(async()=>{try{const result=await api.request<ReleaseJob>(`/admin/releases/${selected.value!.id}`);if(alive){selected.value=result.data;const index=jobs.value.findIndex(job=>job.id===result.data.id);if(index>=0)jobs.value[index]=result.data;}}catch(error){if(alive)issue.value=errorMessage(error);}finally{poll();}},2500);}
async function select(job:ReleaseJob){selected.value=job;issue.value='';poll();}
async function create(){if(!props.changes?.length)return;busy.value=true;issue.value='';try{const result=await api.request<ReleaseJob>('/admin/releases',{method:'POST',body:{changes:props.changes,expectedReleaseId:activeId.value}});selected.value=result.data;jobs.value.unshift(result.data);poll();}catch(error){issue.value=errorMessage(error);}finally{busy.value=false;}}
async function preview(){if(!selected.value)return;busy.value=true;issue.value='';const popup=window.open('about:blank','_blank');try{const response=await api.request<{previewUrl:string}>(`/admin/releases/${selected.value.id}/preview`,{method:'POST',body:{}});const url=new URL(response.data.previewUrl,window.location.origin);if(url.origin!==window.location.origin)throw new Error('预览地址未通过校验。');if(popup){popup.opener=null;popup.location.replace(url.href);}else{issue.value='浏览器阻止了新窗口。已开启预览，可以从侧栏打开网站查看。';}emit('preview',selected.value.releaseId??selected.value.id);}catch(error){popup?.close();issue.value=errorMessage(error);}finally{busy.value=false;}}
async function activate(){if(!selected.value||!window.confirm('确认将这个候选版本设为公开版本？公开页面将切换到已经生成并校验的内容。'))return;busy.value=true;issue.value='';try{const response=await api.request<ReleaseJob>(`/admin/releases/${selected.value.id}/activate`,{method:'POST',body:{expectedReleaseId:activeId.value}});selected.value=response.data;await load();emit('activated');poll();}catch(error){issue.value=errorMessage(error);}finally{busy.value=false;}}
onMounted(async()=>{dialog.value?.showModal();await load();});onBeforeUnmount(()=>{alive=false;if(timer)clearTimeout(timer);});
</script>
<template><dialog ref="dialog" class="release-dialog" aria-labelledby="release-heading" @cancel.prevent="emit('close')"><div class="dialog-head"><div><p class="eyebrow">CONTENT RELEASE</p><h2 id="release-heading">预览与发布</h2></div><button type="button" aria-label="关闭发布窗口" @click="emit('close')">关闭</button></div><div class="dialog-content"><p class="hint">内容先生成私有候选，预览后再切换公开版本。生成或校验失败时，当前公开内容继续保留。</p><div v-if="issue" class="notice error mt16" role="alert">{{issue}}</div><p v-if="loading" class="loading" role="status">正在读取发布记录…</p><template v-else><div v-if="changes?.length&&!selected" class="panel mt24"><h3>本次变更</h3><ul class="change-list"><li v-for="change in changes" :key="`${change.collection}/${change.id}`"><span class="badge">{{change.action==='hide'?'隐藏':'发布'}}</span> {{change.collection}} / {{change.id}} <small>版本 {{change.version}}</small></li></ul><button class="primary mt16" :disabled="busy" @click="create">{{busy?'提交中…':'生成私有候选版本'}}</button></div><section v-if="selected" class="panel mt24"><div class="flex between"><h3>候选版本</h3><span class="badge" :class="{warn:selected.status==='failed',green:selected.status==='ready'||selected.status==='active'}">{{statusLabel(selected.status)}}</span></div><p class="mono mt16">{{selected.releaseId??selected.id}}</p><p class="hint mt8">创建于 {{dateTime(selected.createdAt)}}</p><div v-if="selected.status==='failed'" class="notice error mt16">{{selected.error?.message??'候选版本未通过生成或校验。请检查内容与媒体状态后重新生成。'}} <span v-if="selected.error?.code">（{{selected.error.code}}）</span></div><div v-if="['ready','live','superseded'].includes(selected.status)" class="flex mt24"><button :disabled="busy" @click="preview">打开私有预览 ↗</button><button class="primary" :disabled="busy||selected.id===activeId" @click="activate">{{selected.status==='ready'?'确认发布':'恢复此版本'}}</button></div><p v-else-if="!['live','active','published','failed','cancelled','superseded'].includes(selected.status)" class="hint mt16" role="status">后台正在处理，状态会自动更新。可关闭窗口，稍后从发布记录继续。</p><button v-if="changes?.length" class="text-button mt16" :disabled="busy" @click="selected=null">返回本次变更</button></section><div class="flex between mt32"><h3>发布记录</h3><button :disabled="busy" @click="load">刷新</button></div><p class="hint mt8">当前公开版本：<span class="mono">{{activeId??'尚未发布'}}</span></p><div v-if="!jobs.length" class="empty mt16">还没有发布记录。</div><ul v-else class="release-list mt16"><li v-for="job in jobs" :key="job.id"><button :class="{selected:selected?.id===job.id}" @click="select(job)"><span><strong class="mono">{{job.releaseId??job.id}}</strong><small>{{dateTime(job.createdAt)}}</small></span><span class="badge">{{statusLabel(job.status)}}</span></button></li></ul></template></div></dialog></template>
