<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { api, dateTime, errorMessage, type Collection, type DraftRecord } from '../api';
import DraftPreview from './DraftPreview.vue';
interface Revision { id: string; entryId: string; collection: string; version: number; createdAt: string; data?: Record<string, unknown> }
const props = defineProps<{ collection: Collection; record: DraftRecord<any>; disabled: boolean }>();
const emit = defineEmits<{ restored: [record: DraftRecord<any>]; restoring: [value: boolean]; close: [] }>();
const rows = ref<Revision[]>([]), cursor = ref<string>(), loading = ref(false), issue = ref(''), selected = ref<Revision>(), preview = ref(false), comparing = ref(false), confirmed = ref(false);
let disposed = false, generation = 0;
async function load(more = false) { loading.value = true; issue.value = ''; const current = ++generation;
  try { const response = await api.request<Revision[]>(`/admin/${props.collection}/${props.record.id}/revisions${more && cursor.value ? `?cursor=${encodeURIComponent(cursor.value)}` : ''}`); if (disposed || current !== generation) return; rows.value = [...new Map([...(more ? rows.value : []), ...response.data].map(row => [row.id,row])).values()].sort((a,b) => b.version - a.version); cursor.value = response.meta.nextCursor; }
  catch (error) { if (!disposed && current === generation) issue.value = errorMessage(error); } finally { if (!disposed && current === generation) loading.value = false; }
}
async function choose(row: Revision) { loading.value = true; issue.value = ''; const current = ++generation;
  try { const response = await api.request<Revision>(`/admin/revisions/${row.id}`); if (disposed || current !== generation) return; if (response.data.entryId !== props.record.id || response.data.collection !== props.collection) throw new Error('历史版本不属于当前内容。'); selected.value = response.data; comparing.value = true; confirmed.value = false; }
  catch (error) { if (!disposed) issue.value = errorMessage(error); } finally { if (!disposed && current === generation) loading.value = false; }
}
const changedFields = computed(() => selected.value?.data ? [...new Set([...Object.keys(props.record.draft),...Object.keys(selected.value.data)])].filter(key => JSON.stringify(props.record.draft[key]) !== JSON.stringify(selected.value!.data![key])) : []);
const labels: Record<string,string> = { title:'标题',name:'名称',summary:'摘要',description:'介绍',blocks:'正文内容',photos:'照片与说明',tags:'标签',coverAssetId:'封面',sourceLinks:'来源链接',seo:'搜索资料',series:'系列',sortOrder:'排序',featured:'首页精选',slug:'链接名称',tracks:'曲目',caption:'说明',entryDate:'日期' };
async function restore() { if (!selected.value || props.disabled || !confirmed.value || loading.value) return; loading.value = true; issue.value = '';emit('restoring',true);
  try { const response = await api.request<DraftRecord<any>>(`/admin/${props.collection}/${props.record.id}/restore`, { method: 'POST', body: { revisionId: selected.value.id, expectedVersion: props.record.version } }); if (!disposed) emit('restored', response.data); }
  catch (error) { if (!disposed) issue.value = errorMessage(error); } finally { if (!disposed) {loading.value = false;emit('restoring',false);} }
}
onMounted(() => load()); onBeforeUnmount(() => { disposed = true; generation++; });
</script>
<template><section class="panel mt24 history-panel" aria-label="草稿历史"><div class="flex between"><h2>草稿历史</h2><button type="button" :disabled="loading" @click="emit('close')">收起历史</button></div><p class="hint mt16">恢复会生成新的草稿版本，公开网站在你确认发布前保持原样。较早记录需要逐批查找。</p><p v-if="issue" class="notice error mt16" role="alert">{{issue}}</p><p v-if="disabled" class="notice mt16">请先保存当前修改，再恢复历史版本。</p><ul class="history-rows"><li v-for="row in rows" :key="row.id"><span>版本 {{row.version}} · {{dateTime(row.createdAt)}}</span><button type="button" :disabled="loading" @click="choose(row)">查看与比较</button></li></ul><p v-if="!loading&&!rows.length" class="hint">{{cursor?'这一批未找到匹配版本，可继续查找。':'暂无可显示的历史记录。'}}</p><button v-if="cursor" type="button" :disabled="loading" @click="load(true)">继续查找较早版本</button><button v-if="issue" type="button" :disabled="loading" @click="load()">重新读取历史</button><p v-if="loading" class="hint mt16" role="status">正在读取或保存…</p><div v-if="comparing&&selected?.data" class="history-comparison mt24"><h3>版本 {{selected.version}} 与当前草稿</h3><p class="hint mt8">{{changedFields.length?'发生变化：'+changedFields.map(key=>labels[key]||key).join('、'):'与当前草稿内容相同。'}}</p><details v-for="key in changedFields" :key="key" class="mt16"><summary>{{labels[key]||key}}</summary><div class="history-columns"><div><h4>历史版本</h4><pre>{{JSON.stringify(selected.data[key],null,2)}}</pre></div><div><h4>当前草稿</h4><pre>{{JSON.stringify(record.draft[key],null,2)}}</pre></div></div></details><button type="button" class="mt16" @click="preview=true">预览历史内容</button><label class="check mt16"><input v-model="confirmed" type="checkbox" :disabled="disabled||loading">将此版本恢复为新的草稿</label><button type="button" class="primary mt16" :disabled="disabled||loading||!confirmed" @click="restore">恢复为草稿</button></div><DraftPreview v-if="preview&&selected?.data" :collection="collection" :draft="selected.data as any" @close="preview=false"/></section></template>
<style scoped>.history-rows{list-style:none;padding:0}.history-rows li{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 0;border-bottom:1px solid var(--line)}.history-columns{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:12px}.history-columns>div{min-width:0}.history-columns pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:260px;overflow:auto;background:var(--paper);padding:12px;font-size:11px}@media(max-width:650px){.history-columns{grid-template-columns:1fr}.history-rows li{align-items:flex-start;flex-wrap:wrap}}</style>
