import { describe, expect, it, vi } from 'vitest';
import { PlaylistDraftSchema } from '@xvyin/contracts';
import { createMusicHandler } from '../src/music';
import { emptySnapshot } from '../src/releases';
function snapshot() { const value = emptySnapshot('release_test'); value.playlists.push({ ...PlaylistDraftSchema.parse({ name: 'Original QQ playlist', source: 'tencent', sourceId: '9206816111', enabled: true, isDefault: true }), id: 'qq_main', revisionId: 'revision_test', publishedAt: '2026-09-12T00:00:00.000Z' }); return value; }
const path = (suffix: string, method = 'GET') => new Request(`https://test.xvyin.com/api/v1/music/${suffix}`, { method });
describe('published playlist music boundary', () => {
  it('keeps local playback same-origin and never calls the provider', async () => { const data = snapshot(); data.playlists[0] = { ...PlaylistDraftSchema.parse({ name: 'Local', source: 'local', tracks: [{ id: 'song_1', title: 'Fixture', artist: '', assetId: 'audio_1', coverAssetId: 'cover_1' }] }), id: 'qq_main', revisionId: 'r', publishedAt: '2026-09-12T00:00:00.000Z' }; const fetcher = vi.fn(); const result = await createMusicHandler('https://music.xvyin.com', fetcher)(path('playlist/qq_main'), data, 'req'); expect((await result.json() as any).data[0].url).toBe('/api/v1/media/audio_1/playback'); expect(fetcher).not.toHaveBeenCalled(); });
  it('does not query arbitrary or disabled playlists', async () => { const fetcher = vi.fn(); const handler = createMusicHandler('https://music.xvyin.com', fetcher); await expect(handler(path('playlist/other'), snapshot(), 'req')).rejects.toMatchObject({ status: 404 }); const data = snapshot(); data.playlists[0]!.enabled = false; await expect(handler(path('playlist/qq_main'), data, 'req')).rejects.toMatchObject({ status: 404 }); expect(fetcher).not.toHaveBeenCalled(); });
  it('normalizes the verified live provider shape and hides untrusted artwork', async () => { const fetcher = vi.fn(async (_input: Parameters<typeof fetch>[0], _init?: Parameters<typeof fetch>[1]) => Response.json([{ id: 123, songmid: 'mid1', title: 'Fixture', author: ['A', 'B'], pic: 'https://attacker.invalid/tracking', lrc: 'https://attacker.invalid/lyrics' }])); const response = await createMusicHandler('https://music.xvyin.com', fetcher)(path('playlist/qq_main'), snapshot(), 'request1'); const body = await response.json() as any; expect(body.data).toEqual([{ id: '123', title: 'Fixture', artist: 'A / B', url: '/api/v1/music/stream/qq_main/123', lyrics: '', lyricsUrl: '/api/v1/music/lyrics/qq_main/123' }]); expect(String(fetcher.mock.calls[0]![0])).toContain('id=9206816111'); });
  it('only resolves a published member and redirects to an approved HTTPS media host', async () => { const fetcher = vi.fn().mockResolvedValueOnce(Response.json([{ id: '123', songmid: 'mid1', name: 'Fixture' }])).mockResolvedValueOnce(Response.json({ url: 'https://isure.stream.qqmusic.qq.com/fixture.m4a' })); const response = await createMusicHandler('https://music.xvyin.com', fetcher)(path('stream/qq_main/123'), snapshot(), 'req'); expect(response.status).toBe(307); expect(response.headers.get('location')).toContain('qqmusic.qq.com'); expect(String(fetcher.mock.calls[1]![0])).toContain('id=mid1'); });
  it('rejects provider credentials, lookalike hosts and non-HTTPS destinations', async () => { for (const url of ['http://qq.com/a', 'https://qq.com.attacker.invalid/a', 'https://user:secret@qq.com/a', 'javascript:alert(1)']) { const fetcher = vi.fn().mockResolvedValueOnce(Response.json([{ id: '123' }])).mockResolvedValueOnce(Response.json({ url })); await expect(createMusicHandler('https://music.xvyin.com', fetcher)(path('stream/qq_main/123'), snapshot(), 'req')).rejects.toMatchObject({ status: 503 }); } });
  it('reports provider schema errors as availability failures and returns no body on HEAD', async () => { await expect(createMusicHandler('https://music.xvyin.com', vi.fn(async () => Response.json({ invalid: true })))(path('playlist/qq_main'), snapshot(), 'req')).rejects.toMatchObject({ status: 503 }); const response = await createMusicHandler('https://music.xvyin.com', vi.fn(async () => Response.json([])))(path('playlist/qq_main', 'HEAD'), snapshot(), 'req'); expect(await response.text()).toBe(''); });
});
