/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/api/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=ApiEnv workers/api/worker-configuration.d.ts` (hash: 83cf9e80c218c2404a1746ebaa4ae1d6)
interface __BaseEnv_ApiEnv {
	CONTENT: R2Bucket;
	PUBLIC_ORIGIN: string;
	FIREBASE_PROJECT_ID: string;
	FIRESTORE_DATABASE_ID: string;
	FIRESTORE_EDITION: string;
	BUILD_CODE_SHA: string;
	BUILD_REPOSITORY: string;
	BUILD_REF: string;
	MUSIC_ORIGIN: string;
	GOOGLE_SERVICE_ACCOUNT: string;
	FIREBASE_AUTH_CONFIG: string;
	PRIVACY_SALT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ApiEnv {}
}
interface ApiEnv extends __BaseEnv_ApiEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "FIREBASE_PROJECT_ID" | "FIRESTORE_DATABASE_ID" | "FIRESTORE_EDITION" | "BUILD_CODE_SHA" | "BUILD_REPOSITORY" | "BUILD_REF" | "MUSIC_ORIGIN" | "GOOGLE_SERVICE_ACCOUNT" | "FIREBASE_AUTH_CONFIG" | "PRIVACY_SALT">> {}
}
