import {createHash,randomUUID} from 'node:crypto';
import {createReadStream,createWriteStream} from 'node:fs';
import {chmod,copyFile,lstat,mkdir,mkdtemp,readFile,readdir,realpath,rename,rm,writeFile} from 'node:fs/promises';
import {execFile,spawn} from 'node:child_process';
import {dirname,extname,isAbsolute,relative,resolve,sep} from 'node:path';
import {fileURLToPath} from 'node:url';import {promisify,parseArgs} from 'node:util';
import {z} from 'zod';
import {PublicSnapshotSchema} from '../../apps/web/lib/build-snapshot';

const execute=promisify(execFile);
const UUID=z.string().uuid();const SHA=z.string().regex(/^[a-f0-9]{40}$/u);const HEX256=z.string().regex(/^[a-f0-9]{64}$/u);
const MAX_FILE=25*1024*1024;const MAX_SNAPSHOT=10*1024*1024;
const MIME:Record<string,string>={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.mjs':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/json; charset=utf-8','.txt':'text/plain; charset=utf-8','.xml':'application/xml; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon','.woff':'font/woff','.woff2':'font/woff2','.ttf':'font/ttf','.mp3':'audio/mpeg'};
export class PublishError extends Error{constructor(readonly code:string,message:string){super(message);this.name='PublishError';}}
function check(value:unknown,code:string,message:string):asserts value{if(!value)throw new PublishError(code,message);}
export function validateOrigin(value:string):string{let url:URL;try{url=new URL(value);}catch{throw new PublishError('INVALID_ORIGIN','发布地址无效。');}check(url.protocol==='https:'&&['test.xvyin.com','xvyin.com'].includes(url.hostname)&&!url.port&&!url.username&&!url.password&&!url.search&&!url.hash&&url.pathname==='/', 'INVALID_ORIGIN','发布地址必须是已批准的 HTTPS 网站根地址。');return url.origin;}
export function publicBuildPath(path:string):string{const normalized=path.split(sep).join('/');check(normalized.length>0&&!normalized.startsWith('/')&&!normalized.includes('\\')&&!normalized.split('/').some(part=>!part||part==='.'||part==='..'||part.startsWith('.')),'UNSAFE_BUILD_PATH','生成结果包含不允许的路径。');const encoded='/'+normalized.split('/').map(part=>encodeURIComponent(part)).join('/');check(/^\/[A-Za-z0-9_\-./%]+$/u.test(encoded)&&encoded.length<=500&&!/%(?:2f|5c|2e|00)/iu.test(encoded),'UNSAFE_BUILD_PATH','生成结果包含不允许的路径。');check(!/\.(?:map|ts|tsx|vue|env|log)$/iu.test(normalized),'PRIVATE_BUILD_FILE','生成结果包含源文件或私有日志。');return encoded;}
export function contained(root:string,path:string):boolean{const value=relative(root,path);return value!==''&&!value.startsWith('..'+sep)&&value!=='..'&&!isAbsolute(value);}
async function exists(path:string){try{return await lstat(path);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return null;throw error;}}
async function secureDirectory(path:string){const existing=await exists(path);check(!existing||existing.isDirectory()&&!existing.isSymbolicLink(),'UNSAFE_LOCAL_PATH','本地构建目录不能是符号链接或普通文件。');await mkdir(path,{recursive:true,mode:0o700});if(process.platform!=='win32')await chmod(path,0o700);return realpath(path);}
async function privateJson(path:string,value:unknown){const temporary=path+'.tmp-'+randomUUID();await writeFile(temporary,JSON.stringify(value),{mode:0o600,flag:'wx'});await rename(temporary,path);if(process.platform!=='win32')await chmod(path,0o600);}
async function hashFile(path:string){const hash=createHash('sha256');for await(const chunk of createReadStream(path))hash.update(chunk);return hash.digest('hex');}
export interface BuildFile{path:string;sha256:string;bytes:number;contentType:string}
export async function buildManifest(directory:string,releaseId:string):Promise<{files:BuildFile[]}>{UUID.parse(releaseId);const root=await realpath(directory);const files:BuildFile[]=[];
 async function walk(current:string){for(const entry of(await readdir(current,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name,'en'))){const path=resolve(current,entry.name);check(contained(root,path)&&!entry.isSymbolicLink(),'UNSAFE_BUILD_PATH','生成结果包含链接或越界路径。');if(entry.isDirectory())await walk(path);else{check(entry.isFile(),'UNSAFE_BUILD_FILE','生成结果包含非普通文件。');const info=await lstat(path);check(info.size>0&&info.size<=MAX_FILE,'BUILD_SIZE_LIMIT','静态文件超出服务器允许的大小。');const filePath=publicBuildPath(relative(root,path));if(extname(path)==='.html'){const html=await readFile(path,'utf8');check(html.includes(releaseId)&&/<meta\s[^>]*name=["']xvyin-release["']/u.test(html),'BUILD_RELEASE_MISMATCH','生成的 HTML 缺少对应发布版本。');}files.push({path:filePath,sha256:await hashFile(path),bytes:info.size,contentType:MIME[extname(path).toLowerCase()]??'application/octet-stream'});check(files.length<=5000,'BUILD_FILE_LIMIT','静态文件数量超过服务器上限。');}}}
 await walk(root);check(files.some(file=>file.path==='/index.html'),'BUILD_HOME_MISSING','生成结果缺少首页。');return{files:files.sort((a,b)=>a.path.localeCompare(b.path,'en'))};}
const JobSchema=z.object({id:UUID,codeSha:SHA,status:z.enum(['queued','building','ready','activating','live','superseded','failed','reconciling']),runId:z.string().nullable(),snapshotSha256:HEX256,snapshotPrepared:z.boolean().optional(),preparedAssetCount:z.number().int().nonnegative().optional(),assetCount:z.number().int().nonnegative().optional(),verifiedFileCount:z.number().int().nonnegative().optional(),verifiedIndexCount:z.number().int().nonnegative().optional(),indexCount:z.number().int().nonnegative().optional()}).passthrough();
type Job=z.infer<typeof JobSchema>;
const StateSchema=z.object({schemaVersion:z.literal(1),jobId:UUID,origin:z.string(),codeSha:SHA,mode:z.enum(['local','github']),localRunId:UUID,runId:z.string(),manifestSha256:HEX256.optional(),status:z.string().optional()}).strict();
type RunnerState=z.infer<typeof StateSchema>;
export interface Credentials{cookie:string;csrfToken:string}
const CredentialsSchema=z.object({cookie:z.string().regex(/^__Host-xvyin_session=[A-Za-z0-9_-]{43}$/u),csrfToken:z.string().regex(/^[A-Za-z0-9_-]{43}$/u)}).strict();
export async function readCredentials(path:string):Promise<Credentials>{const info=await lstat(path);check(info.isFile()&&!info.isSymbolicLink()&&info.size<=16384,'INVALID_AUTH_FILE','管理员会话文件无效。');check(process.platform==='win32'||(info.mode&0o077)===0,'AUTH_FILE_PERMISSIONS','会话文件必须仅当前用户可读写（chmod 600）。');try{return CredentialsSchema.parse(JSON.parse(await readFile(path,'utf8')));}catch{throw new PublishError('INVALID_AUTH_FILE','会话文件必须只包含管理员 session Cookie 与 CSRF token。');}}
export function buildEnvironment(source:Record<string,string|undefined>,snapshot:string,origin:string):Record<string,string|undefined>{const env:Record<string,string|undefined>={};for(const[key,value]of Object.entries(source))if(/^(PATH|HOME|USERPROFILE|SYSTEMROOT|WINDIR|COMSPEC|PATHEXT|TEMP|TMP|TMPDIR|APPDATA|LOCALAPPDATA|LANG|LC_ALL)$/iu.test(key))env[key]=value;return{...env,NODE_ENV:'production',CI:'1',NUXT_TELEMETRY_DISABLED:'1',XVYIN_SNAPSHOT_PATH:snapshot,XVYIN_PUBLIC_ORIGIN:origin,XVYIN_INDEXABLE:origin==='https://xvyin.com'?'true':'false'};}
export interface RunnerTransportOptions { origin:string; mode:'local'|'github'; localRunId:string; credentials?:Credentials; environment?:Record<string,string|undefined>; fetch?:typeof fetch; now?:()=>number; requestTimeoutMs?:number }
export function createRunnerTransport(options:RunnerTransportOptions):{request(path:string,init?:RequestInit):Promise<Response>}{const client=new RunnerClient(validateOrigin(options.origin),{mode:options.mode,localRunId:options.localRunId},options.credentials,options.fetch??fetch,options.environment??process.env,options.now??Date.now,options.requestTimeoutMs??60000);return{request:(path,init)=>client.requestRaw(path,init)};}
/** The V3 project's fixed Pages entry transports only authenticated CI internal requests.
 * Both approved site origins use this same verified API service binding, including before apex cutover.
 * Logical Origin, OIDC audience and snapshot URLs retain the selected test or apex origin.
 * Local administrator traffic stays on that logical origin and never uses the Pages transport.
 * No CLI, environment variable, response or user input can supply a replacement transport host. */
export function internalRunnerUrl(origin:string,mode:'local'|'github',path:string):URL{
 const logicalOrigin=validateOrigin(origin),pathname=path.split('?')[0]!;
 check(!/[\\\u0000-\u0020\u007f#]/u.test(path)&&/^\/api\/v1\/internal\/[A-Za-z0-9_-]+(?:\/[A-Za-z0-9_-]+)*$/u.test(pathname),'INVALID_REQUEST_PATH','执行器只可请求本站内部构建接口。');
 const logicalUrl=new URL(path,logicalOrigin);
 check(logicalUrl.origin===logicalOrigin&&logicalUrl.pathname===pathname,'INVALID_REQUEST_PATH','构建请求越过本站边界。');
 const transportOrigin=mode==='github'?'https://xvyin-v3-test.pages.dev':logicalOrigin;
 return new URL(logicalUrl.pathname+logicalUrl.search,transportOrigin);
}
async function rejectCloudflareChallenge(response:Response):Promise<void>{
 if(response.headers.get('cf-mitigated')?.toLowerCase()==='challenge'){
  await response.body?.cancel();throw new PublishError('CLOUDFLARE_CHALLENGE','内部请求被 Cloudflare 浏览器验证拦截；请检查固定执行器入口与后台任务状态。');
 }
}
function nonJsonResponse(response:Response):PublishError{return new PublishError('NON_JSON_RESPONSE',`执行器收到非 JSON 服务响应（HTTP ${response.status}）；请检查站点网关与传输入口，可使用相同命令继续。`);}
export class RunnerClient{
 #cachedToken='';#tokenUntil=0;
 constructor(readonly origin:string,readonly state:Pick<RunnerState,'mode'|'localRunId'>&{jobId?:string},private readonly credentials:Credentials|undefined,private readonly transport:typeof fetch=fetch,private readonly environment:Record<string,string|undefined>=process.env,private readonly now=Date.now,private readonly requestTimeoutMs=60000){this.origin=validateOrigin(origin);}
 async #headers():Promise<Record<string,string>>{if(this.state.mode==='local'){check(this.credentials,'INVALID_AUTH_FILE','缺少管理员会话文件。');return{Origin:this.origin,Cookie:this.credentials.cookie,'X-CSRF-Token':this.credentials.csrfToken,'X-Xvyin-Local-Run':this.state.localRunId};}
  if(this.now()>=this.#tokenUntil){const raw=this.environment.ACTIONS_ID_TOKEN_REQUEST_URL,token=this.environment.ACTIONS_ID_TOKEN_REQUEST_TOKEN;check(raw&&token,'OIDC_UNAVAILABLE','GitHub OIDC 运行环境未配置。');let url:URL;try{url=new URL(raw);}catch{throw new PublishError('OIDC_UNAVAILABLE','GitHub OIDC 运行环境无效。');}check(url.protocol==='https:'&&(url.hostname==='actions.githubusercontent.com'||url.hostname.endsWith('.actions.githubusercontent.com'))&&!url.username&&!url.password,'OIDC_UNAVAILABLE','OIDC 签发地址未通过校验。');url.searchParams.set('audience',`${this.origin}/v3-runner`);let response:Response;try{response=await this.transport(url,{headers:{Authorization:`Bearer ${token}`},redirect:'error',signal:AbortSignal.timeout(15000)});}catch{throw new PublishError('OIDC_UNAVAILABLE','无法获取 GitHub 短期身份。');}check(response.ok,'OIDC_UNAVAILABLE','GitHub 拒绝签发短期身份。');const data=await boundedResponse(response,20000);check(isRecord(data)&&typeof data.value==='string'&&/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/u.test(data.value),'OIDC_UNAVAILABLE','GitHub 返回的短期身份无效。');this.#cachedToken=data.value;this.#tokenUntil=this.now()+180000;}
  return{Origin:this.origin,Authorization:`Bearer ${this.#cachedToken}`};}
 async requestRaw(path:string,init:RequestInit={}):Promise<Response>{const url=internalRunnerUrl(this.origin,this.state.mode,path);const replayable=!init.body||typeof init.body==='string'||init.body instanceof Uint8Array||init.body instanceof Blob;const attempts=replayable?3:1;
  for(let attempt=0;attempt<attempts;attempt++){const headers=new Headers(init.headers);for(const name of ['authorization','cookie','origin','x-csrf-token','x-xvyin-local-run','host','x-forwarded-host','x-forwarded-proto','forwarded','x-forwarded-port'])headers.delete(name);for(const[key,value]of Object.entries(await this.#headers()))headers.set(key,value);headers.set('Accept','application/json');check(Number.isFinite(this.requestTimeoutMs)&&this.requestTimeoutMs>=1000&&this.requestTimeoutMs<=900000,'INVALID_TIMEOUT','执行器超时配置无效。');const own=AbortSignal.timeout(this.requestTimeoutMs);const signal=init.signal?AbortSignal.any([init.signal,own]):own;let response:Response;try{response=await this.transport(url,{...init,headers,redirect:'error',signal});}catch{if(init.signal?.aborted)throw new PublishError('REQUEST_ABORTED','执行已取消。');if(attempt+1<attempts){await delay(500*(attempt+1));continue;}throw new PublishError('NETWORK_ERROR','请求未确认，可使用相同命令继续执行。');}await rejectCloudflareChallenge(response);if((response.status===429||response.status>=500)&&attempt+1<attempts){await response.body?.cancel();await delay(1000*(attempt+1));continue;}if(/^text\/html(?:;|$)/iu.test(response.headers.get('content-type')||'')||!response.ok&&/^text\/plain(?:;|$)/iu.test(response.headers.get('content-type')||'')){await response.body?.cancel();throw nonJsonResponse(response);}return response;}
  throw new PublishError('REQUEST_FAILED','请求未完成。');}
 async request<T>(suffix:string,method='GET',body?:unknown,binary?:Uint8Array):Promise<T>{check(this.state.jobId,'INVALID_ARGUMENTS','缺少发布任务编号。');const response=await this.requestRaw(`/api/v1/internal/releases/${this.state.jobId}${suffix}`,{method,headers:binary?{'Content-Type':'application/octet-stream','Content-Length':String(binary.byteLength)}:body!==undefined?{'Content-Type':'application/json'}:{},...(binary?{body:new Uint8Array(binary)}:body!==undefined?{body:JSON.stringify(body)}:{})});const data=await boundedResponse(response,suffix==='/snapshot'?MAX_SNAPSHOT+1024*1024:5*1024*1024);if(!response.ok){const code=isRecord(data)&&isRecord(data.error)&&typeof data.error.code==='string'&&/^[A-Z0-9_]{1,80}$/u.test(data.error.code)?data.error.code:'REQUEST_FAILED';throw new PublishError(code,'发布服务拒绝了请求，请检查后台任务状态与会话。');}check(isRecord(data)&&'data'in data,'INVALID_RESPONSE','发布服务响应格式无效。');return data.data as T;}
}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
async function boundedResponse(response:Response,max:number):Promise<unknown>{await rejectCloudflareChallenge(response);const contentType=response.headers.get('content-type')||'';if(/^text\/html(?:;|$)/iu.test(contentType)){await response.body?.cancel();throw nonJsonResponse(response);}const reader=response.body?.getReader();check(reader,'INVALID_RESPONSE','发布服务返回空响应。');const chunks:Uint8Array[]=[];let size=0;try{for(;;){const next=await reader.read();if(next.done)break;size+=next.value.byteLength;if(size>max){await reader.cancel();throw new PublishError('RESPONSE_TOO_LARGE','发布响应超出大小限制。');}chunks.push(next.value);}}finally{reader.releaseLock();}const all=new Uint8Array(size);let offset=0;for(const chunk of chunks){all.set(chunk,offset);offset+=chunk.byteLength;}try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(all));}catch{if(!/^application\/(?:[a-z0-9!#$&^_.+-]+\+)?json(?:;|$)/iu.test(contentType))throw nonJsonResponse(response);throw new PublishError('INVALID_RESPONSE','发布服务返回无效 JSON。');}}
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function gitState(root:string):Promise<string>{let head:string;let dirty:string;try{head=(await execute('git',['rev-parse','HEAD'],{cwd:root,windowsHide:true})).stdout.trim();dirty=(await execute('git',['status','--porcelain','--untracked-files=normal'],{cwd:root,windowsHide:true})).stdout;}catch{throw new PublishError('GIT_UNAVAILABLE','无法核对完整 Git 工作副本。');}check(SHA.safeParse(head).success,'INVALID_CODE_SHA','Git 版本无效。');check(!dirty.trim(),'DIRTY_WORKTREE','发布工作副本必须干净，请先保存并提交当前代码。');return head;}
async function copyOutput(source:string,target:string){await mkdir(target,{recursive:true,mode:0o700});for(const entry of await readdir(source,{withFileTypes:true})){const from=resolve(source,entry.name),to=resolve(target,entry.name);check(!entry.isSymbolicLink(),'UNSAFE_BUILD_PATH','生成结果不允许符号链接。');if(entry.isDirectory())await copyOutput(from,to);else{check(entry.isFile(),'UNSAFE_BUILD_FILE','生成结果含非普通文件。');await copyFile(from,to);if(process.platform!=='win32')await chmod(to,0o600);}}}
// Wrangler augments NodeJS.ProcessEnv with required Worker-only secrets. The spawn boundary
// adapts Node's standard string-map environment; buildEnvironment excludes all such secrets.
export async function generateStatic(root:string,privateDir:string,snapshot:string,origin:string){const logPath=resolve(privateDir,'build.log');const log=createWriteStream(logPath,{flags:'w',mode:0o600});const child=spawn(process.execPath,[resolve(root,'node_modules/nuxt/bin/nuxt.mjs'),'generate'],{cwd:resolve(root,'apps/web'),env:buildEnvironment(process.env,snapshot,origin) as NodeJS.ProcessEnv,stdio:['ignore','pipe','pipe'],windowsHide:true});let size=0;const write=(chunk:Buffer)=>{size+=chunk.length;if(size>32*1024*1024)child.kill();else log.write(chunk);};child.stdout.on('data',write);child.stderr.on('data',write);const timer=setTimeout(()=>child.kill(),20*60_000);try{const code=await new Promise<number|null>((yes,no)=>{child.once('error',no);child.once('close',yes);});check(code===0&&size<=32*1024*1024,'BUILD_FAILED','Nuxt 静态生成失败，细节仅保存在私有 build.log。');}finally{clearTimeout(timer);await new Promise<void>(done=>log.end(done));}}
export async function prepareSnapshot(client:RunnerClient,initial:unknown):Promise<Job>{let job=JobSchema.parse(initial),previous=job.preparedAssetCount??0,stalled=0;const started=Date.now();for(let step=0;job.snapshotPrepared===false;step++){check(step<1000&&Date.now()-started<10*60_000,'BUILD_PREPARE_INCOMPLETE','候选准备尚未完成，可使用相同命令继续。');const next=JobSchema.parse(await client.request('/prepare','POST',{}));check(next.id===job.id&&next.codeSha===job.codeSha&&next.runId===job.runId&&next.status==='building','BUILD_STATE_CONFLICT','候选准备结果与执行器不一致。');const current=next.preparedAssetCount??0;check(current>=previous,'INVALID_RESPONSE','候选准备进度倒退。');stalled=current>previous?0:stalled+1;previous=current;job=next;check(job.snapshotPrepared!==false||stalled<3,'BUILD_PREPARE_INCOMPLETE','候选准备暂时没有进展，可使用相同命令继续。');}return job;}
export async function registerBuildManifest(client:RunnerClient,manifest:{files:BuildFile[]}):Promise<void>{let previous=-1,stalled=0;const started=Date.now();for(let step=0;step<1000&&Date.now()-started<10*60_000;step++){const result=await client.request<unknown>('/manifest','POST',manifest);if(isRecord(result)&&result.pending===true){const progress=z.object({pending:z.literal(true),phase:z.literal('assets'),processed:z.number().int().nonnegative(),total:z.number().int().nonnegative()}).strict().parse(result);check(progress.processed<=progress.total&&progress.processed>=previous,'INVALID_RESPONSE','构建清单准备进度无效。');stalled=progress.processed>previous?0:stalled+1;previous=progress.processed;check(stalled<3,'BUILD_MANIFEST_INCOMPLETE','构建清单暂时没有进展，可使用相同命令继续。');continue;}check(isRecord(result)&&result.releaseId===client.state.jobId&&Array.isArray(result.files),'INVALID_RESPONSE','构建服务未返回对应候选清单。');return;}throw new PublishError('BUILD_MANIFEST_INCOMPLETE','构建清单准备尚未完成，可使用相同命令继续。');}
export async function runPublish(options:{jobId:string;origin:string;authFile?:string;root?:string},progress:(message:string)=>void=console.log){const jobId=UUID.parse(options.jobId),origin=validateOrigin(options.origin),root=await realpath(options.root??resolve(dirname(fileURLToPath(import.meta.url)),'../..'));const codeSha=await gitState(root);const privateRoot=await secureDirectory(resolve(root,'.private-build'));check(contained(root,privateRoot),'UNSAFE_LOCAL_PATH','私有构建目录必须位于工作副本内。');const privateDir=await secureDirectory(resolve(privateRoot,jobId));check(contained(privateRoot,privateDir),'UNSAFE_LOCAL_PATH','任务目录无效。');const mode=options.authFile?'local':'github';check(mode==='local'||process.env.GITHUB_ACTIONS==='true','AUTH_REQUIRED','本地执行需要 --auth-file。');const githubRun=process.env.GITHUB_RUN_ID;check(mode==='local'||githubRun&&/^\d+$/u.test(githubRun),'OIDC_UNAVAILABLE','GitHub 运行编号无效。');const statePath=resolve(privateDir,'runner.json');let state:RunnerState;
 if(await exists(statePath)){try{state=StateSchema.parse(JSON.parse(await readFile(statePath,'utf8')));}catch{throw new PublishError('RUNNER_STATE_INVALID','本地续跑记录无效。');}check(state.jobId===jobId&&state.origin===origin&&state.codeSha===codeSha&&state.mode===mode,'RUNNER_STATE_CONFLICT','本地记录的任务、网站、代码或认证方式不一致。');check(mode==='local'||state.runId===`github-${githubRun}`,'RUNNER_STATE_CONFLICT','候选已经被另一次 GitHub 运行领取。');}
 else{const localRunId=randomUUID();state={schemaVersion:1,jobId,origin,codeSha,mode,localRunId,runId:mode==='local'?`local-${localRunId}`:`github-${githubRun}`};await privateJson(statePath,state);}
 const credentials=options.authFile?await readCredentials(resolve(options.authFile)):undefined;const client=new RunnerClient(origin,state,credentials);let job=JobSchema.parse(await client.request(''));check(job.id===jobId&&job.codeSha===codeSha,'BUILD_CODE_MISMATCH','工作副本 HEAD 与候选指定代码不一致。');check(job.runId===null||job.runId===state.runId,'RUNNER_STATE_CONFLICT','候选已由其他执行器领取。');if(['ready','live','superseded'].includes(job.status)){progress(`候选 ${jobId} 已经完成验证；本命令不会激活公开版本。`);return job;}
 check(job.status==='queued'||job.status==='building','BUILD_STATE_CONFLICT','当前任务状态不能继续构建。');job=JobSchema.parse(await client.request('/claim','POST',{}));check(job.codeSha===codeSha&&job.runId===state.runId,'RUNNER_STATE_CONFLICT','执行器领取结果不匹配。');progress('执行器已认证，正在读取私有候选。');try{
 job=await prepareSnapshot(client,job);const downloaded=await client.request<unknown>('/snapshot');const serialized=JSON.stringify(downloaded);check(createHash('sha256').update(serialized).digest('hex')===job.snapshotSha256,'SNAPSHOT_HASH_MISMATCH','候选快照摘要不匹配。');const snapshot=PublicSnapshotSchema.parse(downloaded);check(snapshot.releaseId===jobId,'SNAPSHOT_RELEASE_MISMATCH','候选快照版本不匹配。');const snapshotPath=resolve(privateDir,'snapshot.json');await privateJson(snapshotPath,downloaded);
 const output=resolve(privateDir,'public');if(!await exists(output)){progress('正在生成静态页面；详细输出仅写入私有日志。');await generateStatic(root,privateDir,snapshotPath,origin);const generated=resolve(root,'apps/web/.output/public');await buildManifest(generated,jobId);const stage=await mkdtemp(resolve(privateDir,'public-stage-'));try{await copyOutput(generated,stage);await rename(stage,output);}finally{if(await exists(stage)){const real=await realpath(stage);check(contained(privateDir,real),'UNSAFE_LOCAL_PATH','临时目录越界。');await rm(real,{recursive:true,force:true});}}}
 check(!(await lstat(output)).isSymbolicLink(),'UNSAFE_LOCAL_PATH','候选输出不能是符号链接。');const manifest=await buildManifest(output,jobId),manifestSha=createHash('sha256').update(JSON.stringify(manifest)).digest('hex');if(state.manifestSha256)check(state.manifestSha256===manifestSha,'IMMUTABLE_BUILD_CHANGED','本地候选文件已改变，不能覆盖不可变发布。');state.manifestSha256=manifestSha;await privateJson(resolve(privateDir,'manifest.json'),manifest);await privateJson(statePath,state);await registerBuildManifest(client,manifest);progress(`清单已确认，正在上传 ${manifest.files.length} 个静态文件。`);
 for(const file of manifest.files){const path=resolve(output,decodeURIComponent(file.path).slice(1));check(contained(output,path),'UNSAFE_BUILD_PATH','上传文件越界。');const binary=new Uint8Array(await readFile(path));check(binary.byteLength===file.bytes&&createHash('sha256').update(binary).digest('hex')===file.sha256,'IMMUTABLE_BUILD_CHANGED','待上传文件在校验后发生变化。');await client.request(`/file?path=${encodeURIComponent(file.path)}`,'PUT',undefined,binary);}
 let previousProgress=-1,stalled=0;
 for(let attempt=0;attempt<1000;attempt++){try{job=JobSchema.parse(await client.request('/finish','POST',{}));}catch(error){const observed=JobSchema.parse(await client.request(''));if(['ready','live','superseded'].includes(observed.status))job=observed;else throw error;}if(['ready','live','superseded'].includes(job.status)){state.status=job.status;await privateJson(statePath,state);progress(`候选 ${jobId} 已就绪。请回到后台预览，再确认发布。`);return job;}check(job.status==='building','BUILD_STATE_CONFLICT','候选状态已改变，请检查后台。');const currentProgress=(job.verifiedFileCount??0)+(job.verifiedIndexCount??0);stalled=currentProgress>previousProgress?0:stalled+1;previousProgress=currentProgress;check(stalled<3,'BUILD_VERIFY_INCOMPLETE','候选校验暂时没有进展，可使用相同命令继续。');}
 throw new PublishError('BUILD_VERIFY_INCOMPLETE','候选校验尚未完成，可使用相同命令继续。');}catch(error){const code=deterministicFailure(error);if(code){try{await client.request('/fail','POST',{code});}catch{/* Keep the original error and never print private logs. */}}throw error;}}
export function deterministicFailure(error:unknown):'NUXT_BUILD_FAILED'|'CONTENT_VALIDATION_FAILED'|'BUILD_INTEGRITY_FAILED'|null{
 if(error instanceof z.ZodError)return'CONTENT_VALIDATION_FAILED';
 if(!(error instanceof PublishError))return null;
 if(error.code==='BUILD_FAILED')return'NUXT_BUILD_FAILED';
 if(['SNAPSHOT_HASH_MISMATCH','SNAPSHOT_RELEASE_MISMATCH','BUILD_RELEASE_MISMATCH','UNSAFE_BUILD_PATH','PRIVATE_BUILD_FILE','BUILD_SIZE_LIMIT','BUILD_FILE_LIMIT','BUILD_HOME_MISSING','IMMUTABLE_BUILD_CHANGED','BUILD_ROUTE_MISSING','BUILD_HTML_INVALID','MANIFEST_CONFLICT','BUILD_FILE_MISMATCH','BUILD_SIZE_MISMATCH','IMMUTABLE_FILE_CONFLICT'].includes(error.code))return'BUILD_INTEGRITY_FAILED';
 return null;
}
const invoked=process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url);
if(invoked){try{const {values}=parseArgs({options:{job:{type:'string'},origin:{type:'string'},'auth-file':{type:'string'},help:{type:'boolean'}},strict:true});if(values.help){console.log('生成私有内容候选（不会激活）：\nnode --import tsx scripts/v3/publish.ts --job <UUID> --origin https://test.xvyin.com --auth-file <私有会话JSON>\nGitHub Actions 使用 OIDC，不传 --auth-file。');}else{check(values.job&&values.origin,'INVALID_ARGUMENTS','需要 --job 与 --origin。');await runPublish({jobId:values.job,origin:values.origin,authFile:values['auth-file']});}}catch(error){console.error(error instanceof PublishError?`${error.code}: ${error.message}`:'PUBLISH_FAILED: 执行未完成，请核对参数、配置与私有日志。');process.exitCode=1;}}
