<script setup lang="ts">
import { assetVariant, displayTime, safeUrl } from '~/lib/site'
import { parseLyrics } from '~/lib/lyrics'
const music = useMusic()
const { playlists, playlistId, tracks, track, source, index, playing, duration, position, volume, loading, error, repeat, lyrics, lyricsLoading, lyricsError } = music
const playlistOpen = ref(false), lyricsOpen = ref(false)
const cover = computed(() => safeUrl(track.value?.coverUrl) || assetVariant(track.value?.coverAssetId, 'thumb')?.url)
const lyricLines = computed(() => parseLyrics(lyrics.value))
const activeLyric = computed(() => { let result = -1; lyricLines.value.forEach((line, i) => { if (line.time >= 0 && line.time <= position.value) result = i }); return result })
watch([lyricsOpen, () => track.value?.id, () => track.value?.lyricsUrl], () => { if (lyricsOpen.value) void music.loadLyrics() })
</script>
<template><section class="panel music-panel" aria-labelledby="music-title"><div class="panel-head"><h3 id="music-title">我的音乐</h3><div><button class="quiet" @click="playlistOpen = true">歌单</button><button class="quiet" @click="lyricsOpen = true">歌词</button></div></div>
  <div class="track"><img v-if="cover" :src="cover" class="track-cover" alt="" width="76" height="76" loading="lazy"><span v-else class="disc" aria-hidden="true"><SiteIcon name="music" :size="30" /></span><div><h4>{{ track?.title || '选择一首，慢慢听。' }}</h4><p>{{ track?.artist || (loading ? '正在加载歌单' : '未选择曲目') }}</p></div></div>
  <input class="progress" type="range" min="0" :max="Number.isFinite(duration) ? duration : 0" :value="position" :disabled="!Number.isFinite(duration)" aria-label="播放进度" @input="music.seek(Number(($event.target as HTMLInputElement).value))">
  <div class="times"><span>{{ displayTime(position) }}</span><span>{{ displayTime(duration) }}</span></div>
  <div class="controls"><button class="icon-button" aria-label="单曲循环" :aria-pressed="repeat" @click="repeat = !repeat"><SiteIcon name="repeat" /></button><button class="icon-button" aria-label="上一首" :disabled="tracks.length < 2" @click="music.previous"><SiteIcon name="previous" /></button><button class="play-button primary" :aria-label="playing ? '暂停音乐' : '播放音乐'" :disabled="!source" @click="music.toggle"><SiteIcon :name="playing ? 'pause' : 'play'" /></button><button class="icon-button" aria-label="下一首" :disabled="tracks.length < 2" @click="music.next"><SiteIcon name="next" /></button><label class="volume-desktop"><SiteIcon name="volume" /><input type="range" class="volume" min="0" max="1" step=".05" :value="volume" aria-label="音乐音量" @input="music.setVolume(Number(($event.target as HTMLInputElement).value))"></label></div>
  <p v-if="error" class="feedback error" role="status">{{ error }} <button class="quiet" :disabled="loading" @click="music.refresh">重试</button></p><div class="music-footer"><span>{{ playing ? '正在播放' : '点击播放后才开始聆听' }}</span><a v-if="safeUrl(track?.sourceUrl)" :href="safeUrl(track?.sourceUrl)" target="_blank" rel="noopener noreferrer">原平台 <SiteIcon name="external" :size="16" /></a></div>
  <AppDialog v-model="playlistOpen" title="我的歌单"><label class="field">选择歌单<select :value="playlistId" :disabled="loading || !playlists.length" @change="music.selectPlaylist(($event.target as HTMLSelectElement).value)"><option v-if="!playlists.length" value="">尚无公开歌单</option><option v-for="playlist in playlists" :key="playlist.id" :value="playlist.id">{{ playlist.title }}</option></select></label><p v-if="loading" role="status">正在加载曲目…</p><p v-else-if="!tracks.length" class="muted">这个歌单暂时没有可播放曲目。</p><ol class="track-list"><li v-for="(item, i) in tracks" :key="item.id"><button :aria-current="i === index ? 'true' : undefined" @click="i === index ? music.toggle() : music.selectTrack(i)"><span>{{ item.title }}<small>{{ item.artist }}</small></span><SiteIcon :name="i === index && playing ? 'pause' : 'play'" /></button></li></ol><p v-if="error" class="feedback error">{{ error }}</p></AppDialog>
  <AppDialog v-model="lyricsOpen" :title="track?.title ? `${track.title} · 歌词` : '歌词'"><p v-if="lyricsLoading" class="muted" role="status">正在读取歌词…</p><p v-else-if="lyricsError" class="feedback error" role="status">{{ lyricsError }} <button class="quiet" @click="music.loadLyrics(true)">重试</button></p><div v-else-if="lyricLines.length" class="lyrics"><p v-for="(line, i) in lyricLines" :key="i" :class="{ current: i === activeLyric }">{{ line.text }}</p></div><p v-else class="muted">这首歌暂时没有歌词，仍可继续聆听。</p></AppDialog>
</section></template>
