<script setup lang="ts">
import { assetVariant, displayDate, ordered, type Photo } from '~/lib/site'
const props = withDefaults(defineProps<{ photos: Photo[]; layout?: string }>(), { layout: 'grid' })
const pictures = computed(() => ordered(props.photos)), open = ref(false), active = ref(0)
const continuous = computed(() => ['continuous', 'stack'].includes(props.layout) || pictures.value.length === 1)
function portrait(item: Photo) { const variant = assetVariant(item.assetId); return Boolean(variant?.width && variant?.height && variant.height > variant.width * 1.1) }
const photo = computed(() => pictures.value[active.value])
const large = computed(() => assetVariant(photo.value?.assetId, 'large'))
const failed = ref<Record<string, boolean>>({})
function show(i: number) { active.value = i; open.value = true }
function navigate(delta: number) { active.value = (active.value + delta + pictures.value.length) % pictures.value.length }
function keyboard(event: KeyboardEvent) { if (!open.value) return; if (event.key === 'ArrowLeft') navigate(-1); if (event.key === 'ArrowRight') navigate(1) }
onMounted(() => window.addEventListener('keydown', keyboard))
onBeforeUnmount(() => window.removeEventListener('keydown', keyboard))
</script>

<style scoped>
.gallery-frame{align-items:start;gap:clamp(24px,3vw,40px) clamp(16px,2.5vw,28px);width:100%;min-width:0}.gallery-frame figure{margin:0;min-width:0;align-self:start}.gallery-frame .photo-button{height:auto;max-height:none;min-height:0;display:block;background:transparent!important;line-height:0;overflow:hidden}.gallery-frame img{width:100%;height:auto;max-height:680px;max-height:min(78svh,760px);object-fit:contain;object-position:center;display:block}.gallery-frame.photo-gallery-continuous{max-width:none}.gallery-frame.photo-gallery-continuous .portrait-photo{width:min(100%,480px);justify-self:center}.gallery-frame .photo-button:hover img{opacity:.94}.gallery-frame figcaption{margin:12px auto 0;text-align:left;line-height:1.75;max-width:42rem;overflow-wrap:anywhere}.gallery-frame figcaption strong{font-size:18px;font-weight:400}.gallery-frame figcaption time{font-size:12px;margin-top:5px;font-variant-numeric:tabular-nums}.gallery-frame .expand-icon{width:34px;height:34px;right:10px;top:10px;opacity:0;transition:opacity .15s}.gallery-frame .photo-button:is(:hover,:focus-visible) .expand-icon{opacity:1}.gallery-frame.gallery-columns{display:block;columns:2;column-gap:24px}.gallery-columns figure{break-inside:avoid;margin-bottom:30px}.gallery-columns img{max-height:none}.gallery-frame .media-unavailable{min-height:180px;display:grid;place-content:center}.lightbox-body>img{background:transparent;object-fit:contain}.lightbox-caption{max-width:42rem;margin-inline:auto}
@media(hover:none){.gallery-frame .expand-icon{opacity:.8}}
@media(max-width:600px){.gallery-frame:not(.photo-gallery-continuous){grid-template-columns:minmax(0,1fr)}.gallery-frame.gallery-columns{columns:1}.gallery-frame img{max-height:78svh}.gallery-frame figcaption{font-size:13px;margin-top:10px}.gallery-frame.photo-gallery-continuous .portrait-photo{width:min(100%,440px)}}
</style>
<template><div :class="['photo-gallery', 'gallery-frame', { 'photo-gallery-continuous': continuous, 'gallery-columns': layout === 'columns' }]"><figure v-for="(item, i) in pictures" :key="item.id || `${item.assetId}/${i}`" :class="{ 'portrait-photo': portrait(item) }"><button v-if="assetVariant(item.assetId) && !failed[item.assetId]" class="photo-button" :aria-label="`放大查看${item.title || item.alt || '照片'}`" @click="show(i)"><img :src="assetVariant(item.assetId)?.url" :width="assetVariant(item.assetId)?.width" :height="assetVariant(item.assetId)?.height" :alt="item.alt" loading="lazy" decoding="async" @error="failed[item.assetId] = true"><span class="expand-icon"><SiteIcon name="expand" /></span></button><div v-else class="media-unavailable"><p>照片暂时无法显示。</p><button v-if="failed[item.assetId]" @click="failed[item.assetId] = false">重新加载</button></div><figcaption v-if="item.title || item.caption || item.photoDate"><strong v-if="item.title">{{ item.title }}</strong><span v-if="item.caption">{{ item.caption }}</span><time v-if="item.photoDate" :datetime="item.photoDate">{{ displayDate(item.photoDate) }}</time></figcaption></figure></div><AppDialog v-model="open" :title="photo?.title || '查看照片'" wide><div v-if="photo" class="lightbox-body"><img v-if="large && open" :src="large.url" :alt="photo.alt" :width="large.width" :height="large.height"><p v-else-if="open">照片暂时无法显示。</p><div class="lightbox-caption"><p v-if="photo.caption">{{ photo.caption }}</p><time v-if="photo.photoDate" :datetime="photo.photoDate">{{ displayDate(photo.photoDate) }}</time></div></div><div v-if="pictures.length > 1" class="lightbox-nav"><button aria-label="上一张照片" @click="navigate(-1)"><SiteIcon name="back" />上一张</button><span>{{ active + 1 }} / {{ pictures.length }}</span><button aria-label="下一张照片" @click="navigate(1)">下一张<SiteIcon name="arrow" /></button></div></AppDialog></template>
