import { describe,it,expect,vi } from 'vitest';
import { AdminApi,ApiError,mediaPreview } from '../src/api';
const success=(data:unknown)=>new Response(JSON.stringify({data,meta:{requestId:'test-request',schemaVersion:1}}),{status:200});
describe('administrator browser transport',()=>{
 it('keeps credentials on the local API and sends CSRF on writes',async()=>{const fetcher=vi.fn().mockResolvedValue(success({id:'saved'}));const api=new AdminApi(fetcher);api.csrfToken='test-csrf';await api.request('/admin/creations',{method:'POST',body:{draft:{title:'本地测试'}}});expect(fetcher).toHaveBeenCalledWith('/api/v1/admin/creations',expect.objectContaining({credentials:'include',cache:'no-store',method:'POST',headers:expect.objectContaining({'X-CSRF-Token':'test-csrf','Content-Type':'application/json'}),body:JSON.stringify({draft:{title:'本地测试'}})}));});
 it('uploads a raw Blob without JSON or exposing a token in the URL',async()=>{const fetcher=vi.fn().mockResolvedValue(success({partNumber:1,bytes:3,etag:'test'}));const api=new AdminApi(fetcher);api.csrfToken='test-csrf';const blob=new Blob(['abc']);await api.request('/admin/media/uploads/test/parts/1',{method:'PUT',rawBody:blob});expect(fetcher).toHaveBeenCalledWith('/api/v1/admin/media/uploads/test/parts/1',expect.objectContaining({body:blob,headers:expect.objectContaining({'Content-Type':'application/octet-stream','X-CSRF-Token':'test-csrf'})}));});
 it('retains validation details and request ID for a version conflict',async()=>{const api=new AdminApi(vi.fn().mockResolvedValue(new Response(JSON.stringify({error:{code:'VERSION_CONFLICT',message:'内容已更新',fields:{version:['需要重新读取']}},meta:{requestId:'trace-1',schemaVersion:1}}),{status:409})));await expect(api.request('/admin/creations/id',{method:'PATCH',body:{}})).rejects.toMatchObject({status:409,code:'VERSION_CONFLICT',requestId:'trace-1',fields:{version:['需要重新读取']}});});
 it('requests reauthentication on a revoked session, not on invalid login',async()=>{const fetcher=vi.fn().mockImplementation(()=>Promise.resolve(new Response(JSON.stringify({error:{code:'SESSION_REVOKED',message:'需要登录'},meta:{requestId:'test',schemaVersion:1}}),{status:401})));const api=new AdminApi(fetcher);api.onExpired=vi.fn();await expect(api.request('/auth/login',{method:'POST',body:{}})).rejects.toBeInstanceOf(ApiError);expect(api.onExpired).not.toHaveBeenCalled();await expect(api.request('/admin/creations')).rejects.toBeInstanceOf(ApiError);expect(api.onExpired).toHaveBeenCalledTimes(1);});
 it('does not turn a network failure containing credentials into displayed text',async()=>{const api=new AdminApi(vi.fn().mockRejectedValue(new Error('upstream secret-password / token-secret')));try{await api.request('/auth/login',{method:'POST',body:{password:'secret-password'}});throw new Error('Expected rejection');}catch(error){expect(error).toMatchObject({code:'NETWORK_ERROR'});expect(String(error)).not.toContain('secret-password');expect(String(error)).not.toContain('token-secret');}});
 it('fails closed when a service returns an HTML page or invalid envelope',async()=>{const api=new AdminApi(vi.fn().mockResolvedValue(new Response('<html>login</html>',{status:200})));await expect(api.request('/admin/creations')).rejects.toMatchObject({code:'INVALID_RESPONSE'});});
 it('shows only an authenticated media variant endpoint and no unready preview',()=>{const item={id:'test-asset',kind:'image' as const,originalBytes:8,status:'ready',variants:[{role:'thumb',url:'https://untrusted.invalid/private-token'}]};expect(mediaPreview(item)).toBe('/api/v1/admin/media/test-asset/thumb');expect(mediaPreview({...item,status:'processing'})).toBeUndefined();});
});
