// Isolated headless UI verification; run against browser-fixture.ts, never a cloud hostname.
import { chromium } from 'playwright-core';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';
const origin='http://127.0.0.1:5194';const output=resolve(import.meta.dirname,'../../../..','admin-ui-qa');await mkdir(output,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.XVYIN_TEST_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1050}});const page=await context.newPage();const errors=[];const writes=[];const entryTitle='本地 UI 测试：混合内容 · '+crypto.randomUUID().slice(0,8);
page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('401'))errors.push(message.text());});page.on('request',request=>{if(['POST','PATCH'].includes(request.method())&&request.url().includes('/admin/creations'))writes.push({url:request.url(),csrf:!!request.headers()['x-csrf-token'],body:request.postDataJSON()});});page.on('dialog',dialog=>dialog.accept());
const shot=async name=>{await page.waitForFunction(()=>window.innerWidth>760||!document.querySelector('.sidebar')||document.querySelector('.sidebar').getBoundingClientRect().right<=0);return page.screenshot({path:resolve(output,name+'.png'),fullPage:false});};const nav=async label=>{await page.locator('.sidebar nav button').filter({hasText:label}).click();await page.locator('.page-heading h1').filter({hasText:label}).waitFor();};
try{
 await page.goto(origin+'/admin/');await page.getByRole('heading',{name:'欢迎回来'}).waitFor();assert.match(await page.title(),/本地 UI 验证/);await shot('01-login-desktop');
 await page.getByLabel('管理员账号',{exact:true}).fill('ui-fixture');await page.getByLabel('密码',{exact:true}).fill('test-only-not-a-real-account');await page.getByRole('button',{name:'登录管理后台',exact:true}).click();await page.locator('.page-heading h1').filter({hasText:'总览'}).waitFor();await shot('02-overview-desktop');
 await nav('创作');await page.getByRole('button',{name:'＋ 新建创作',exact:true}).click();await page.getByLabel('创作标题',{exact:true}).fill(entryTitle);await page.getByPlaceholder('my-creation',{exact:true}).fill('local-ui-check');await page.getByLabel('摘要',{exact:true}).fill('这条记录只存在于本地验证进程，不会发布。');await page.getByRole('button',{name:'＋ 富文本',exact:true}).click();await page.getByRole('textbox',{name:'第1块富文本'}).fill('测试正文：文字通过结构化内容保存。');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByRole('status').filter({hasText:'草稿已保存'}).waitFor();assert.equal(writes.length,1);assert.equal(writes[0].csrf,true);assert.equal(writes[0].body.draft.blocks[0].type,'richtext');assert.match(JSON.stringify(writes[0].body.draft.blocks),/测试正文/);
 for(const label of ['图片','图集','音频','视频','引用','代码','附件'])await page.getByRole('button',{name:`＋ ${label}`,exact:true}).click();assert.equal(await page.locator('.block-editor>.content-block').count(),8);await page.getByRole('button',{name:'将第2个内容块上移',exact:true}).click();assert.match(await page.locator('.block-editor>.content-block').first().innerText(),/图片/);await page.getByRole('button',{name:'将第1个内容块下移',exact:true}).click();await page.evaluate(()=>window.scrollTo(0,0));await shot('03-mixed-editor-desktop');
 await nav('摄影');await page.getByRole('button',{name:'＋ 新建摄影',exact:true}).click();await page.getByRole('button',{name:'＋ 添加照片',exact:true}).click();assert.equal(await page.getByLabel('发布状态').inputValue(),'draft');await page.getByRole('button',{name:'选择媒体',exact:true}).first().click();await page.getByRole('dialog').getByRole('heading',{name:'暂无可选媒体'}).waitFor();await page.getByRole('button',{name:'关闭媒体选择'}).click();
 await nav('健身');await page.getByText('开始日期为空，前台不显示天数',{exact:true}).waitFor();assert.equal(await page.getByLabel('真实开始日期').inputValue(),'');await shot('04-fitness-desktop');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByRole('status').filter({hasText:'草稿已保存'}).waitFor();
 await nav('歌单');await page.getByRole('button',{name:'＋ 新建歌单',exact:true}).click();await page.getByLabel('歌单名称',{exact:true}).fill('本地验证歌单');await page.getByRole('button',{name:'＋ 添加曲目',exact:true}).click();await page.getByLabel('曲名',{exact:true}).fill('测试曲目');await page.getByLabel('曲目来源').selectOption('provider');await page.getByLabel('歌曲 ID',{exact:true}).fill('123');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByRole('status').filter({hasText:'草稿已保存'}).waitFor();
 await nav('评论审核');await page.getByRole('heading',{name:'还没有访客留言'}).waitFor();await page.getByRole('tab',{name:'私密联系'}).click();await page.getByRole('heading',{name:'还没有收到联系'}).waitFor();await nav('媒体');await page.getByRole('heading',{name:'媒体库还是空的'}).waitFor();await nav('统计');await page.getByText('尚未接入',{exact:true}).waitFor();await nav('设置');await page.getByLabel('首页招呼').waitFor();assert.equal(await page.getByLabel('首页招呼').inputValue(),'Hello! I am 虚宁');await page.getByRole('textbox',{name:'关于我的正文'}).fill('本地设置验证。');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByRole('status').filter({hasText:'草稿已保存'}).waitFor();await shot('05-settings-desktop');
 await page.getByRole('button',{name:'发布中心',exact:true}).click();await page.getByRole('tab',{name:'发布记录',exact:true}).click();await page.getByRole('dialog').getByText('还没有发布记录。',{exact:true}).waitFor();await page.getByRole('button',{name:'关闭发布窗口'}).click();
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'打开管理导航'}).click();await nav('健身');await page.getByText('开始日期为空，前台不显示天数',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);await shot('06-fitness-mobile');
 await page.getByRole('button',{name:'打开管理导航'}).click();await nav('创作');await page.getByRole('button',{name:entryTitle,exact:true}).click();await page.getByRole('textbox',{name:'第1块富文本'}).waitFor();assert.equal(await page.locator('.block-editor>.content-block').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);await shot('07-editor-mobile');
 assert.deepEqual(errors,[]);await writeFile(resolve(output,'result.json'),JSON.stringify({passed:true,scope:'Local UI with real createApi, test auth and MemoryStore; no external deployment/media processing verified',viewports:['1440x1050','390x844'],assertions:['login/session','actual draft POST and CSRF','all eight blocks and reorder','media-picker empty state','photo visibility selection','fitness null date persisted','playlist external track saved','comments/contacts empty states','unavailable traffic','site settings saved','release empty state','mobile no horizontal overflow','saved editor reload'],consoleErrors:errors},null,2));console.log(JSON.stringify({passed:true,output,consoleErrors:errors}));
}catch(error){await shot('failure');console.error(error);console.error(JSON.stringify({errors,writes:writes.map(item=>({url:item.url,csrf:item.csrf}))}));process.exitCode=1;}finally{await browser.close();}
