import { describe, expect, it } from 'vitest';
import { acknowledgeSnapshot, clearOwnerRecovery, listRecovery, MAX_RECOVERY_BYTES, parseRecovery, RECOVERY_TTL, recoveryKey, removeCapturedRecovery, removeRecovery, writeRecovery, type RecoveryRecord } from '../src/draft-recovery';
function storage(){const data=new Map<string,string>();return {get length(){return data.size;},key:(index:number)=>[...data.keys()][index]??null,getItem:(key:string)=>data.get(key)??null,setItem:(key:string,value:string)=>{data.set(key,value);},removeItem:(key:string)=>{data.delete(key);}};}
const now=1790737200000;
const record=(values:Partial<RecoveryRecord>={}):RecoveryRecord=>({schemaVersion:1,owner:'owner',collection:'creations',entryId:'first',tabId:'tab-a',baseVersion:2,updatedAt:now,snapshot:{draft:{title:'保留中文',summary:'',blocks:[],tags:[],sourceLinks:[],seo:{}},tagText:'未完成，',sourceText:'https://unfinished'},...values});
describe('private draft recovery and save acknowledgements',()=>{
  it('keeps concurrent tabs isolated and does not clear another pending draft on save',()=>{const store=storage();writeRecovery(store,record());writeRecovery(store,record({tabId:'tab-b'}));removeRecovery(store,record());expect(listRecovery(store,'owner','creations','first',now).map(row=>row.tabId)).toEqual(['tab-b']);});
  it('scopes recovery to authenticated identity, collection and entry',()=>{const store=storage();writeRecovery(store,record());writeRecovery(store,record({owner:'someone-else'}));writeRecovery(store,record({entryId:'second'}));expect(listRecovery(store,'owner','creations','first',now)).toHaveLength(1);expect(listRecovery(store,'owner','albums','first',now)).toHaveLength(0);clearOwnerRecovery(store,'owner');expect(store.length).toBe(1);expect(listRecovery(store,'someone-else','creations','first',now)).toHaveLength(1);});
  it('preserves newer edits after a slow request acknowledgement',()=>{expect(acknowledgeSnapshot('sent document','newly typed text')).toEqual({dirty:true,clearRecovery:false});expect(acknowledgeSnapshot('same','same')).toEqual({dirty:false,clearRecovery:true});});
  it('recovers incomplete form fields rather than silently dropping invalid URLs or raw tag input',()=>{const store=storage();writeRecovery(store,record());expect(listRecovery(store,'owner','creations','first',now)[0]!.snapshot.sourceText).toBe('https://unfinished');expect(listRecovery(store,'owner','creations','first',now)[0]!.snapshot.tagText).toBe('未完成，');});
  it('rejects corrupted, oversized, future or expired envelopes and retains original storage for inspection',()=>{expect(parseRecovery('{broken',now)).toBeNull();expect(parseRecovery(JSON.stringify(record({updatedAt:now+120000})),now)).toBeNull();expect(parseRecovery(JSON.stringify(record()),now+RECOVERY_TTL+1)).toBeNull();expect(parseRecovery(JSON.stringify({...record(),snapshot:{draft:null,tagText:'',sourceText:''}}),now)).toBeNull();expect(parseRecovery(' '.repeat(MAX_RECOVERY_BYTES+1),now)).toBeNull();});
  it('does not silently evict another unfinished draft when the bounded cache is full',()=>{const store=storage();for(let i=0;i<20;i++)writeRecovery(store,record({tabId:'tab-'+i}));expect(()=>writeRecovery(store,record({tabId:'new'}))).toThrow();expect(store.length).toBe(20);writeRecovery(store,record({tabId:'tab-0',baseVersion:3}));expect(parseRecovery(store.getItem(recoveryKey('owner','creations','first','tab-0')),now)?.baseVersion).toBe(3);});
  it('propagates blocked storage so UI can request local export instead of falsely claiming saved',()=>{const store=storage();store.setItem=()=>{throw new Error('quota');};expect(()=>writeRecovery(store,record())).toThrow('quota');});
  it('moves pending new-record recovery to the returned server id without altering its snapshot',()=>{const store=storage();const first=record({entryId:'new',baseVersion:0});writeRecovery(store,first);const next={...first,entryId:'server-created',baseVersion:1};writeRecovery(store,next);removeRecovery(store,first);expect(listRecovery(store,'owner','creations','new',now)).toEqual([]);expect(listRecovery(store,'owner','creations','server-created',now)[0]!.snapshot).toEqual(first.snapshot);});
  it('does not remove a newer foreign slot after restoring an older captured prompt',()=>{const store=storage(),captured=record();writeRecovery(store,captured);writeRecovery(store,{...captured,updatedAt:now+1,snapshot:{...captured.snapshot,tagText:'另一个标签页刚输入'}});expect(removeCapturedRecovery(store,captured)).toBe(false);expect(listRecovery(store,'owner','creations','first',now+1)[0]!.snapshot.tagText).toBe('另一个标签页刚输入');});
  it('removes an unchanged adopted slot after it was safely copied',()=>{const store=storage(),captured=record();writeRecovery(store,captured);writeRecovery(store,{...captured,tabId:'tab-b'});expect(removeCapturedRecovery(store,captured)).toBe(true);expect(listRecovery(store,'owner','creations','first',now)).toHaveLength(1);});
});
